version: 2.1

plain-go: &plain-go
  working_directory: /home/circleci/dd-trace-go.v1
  docker:
    - image: circleci/golang:latest
      environment:
        GOPATH: "/home/circleci/go"

jobs:
  test-core:
    parallelism: 4
    parameters:
      gover:
        type: string
      build_tags:
        description: "go build tags to use to compile the tests"
        default: ""
        type: string
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    resource_class: xlarge
    docker:
      - image: circleci/golang:<< parameters.gover >>
        environment:
          GOPATH: "/home/circleci/go"
    working_directory: /home/circleci/dd-trace-go.v1
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            mkdir -p $TEST_RESULTS
            cp go.sum go.sum.orig
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v5-core-<< parameters.gover >>-{{ checksum "go.sum.orig" }}
      - run:
          name: Tidy Modules
          command: GO111MODULE=on go mod tidy || exit 0 # this step can fail and we don't care.
      - run:
          name: Testing
          command: |
            PACKAGE_NAMES=$(go list ./... | grep -v /contrib/ | circleci tests split --split-by=timings --timings-type=classname)
            export DD_APPSEC_ENABLED=$(test "<< parameters.build_tags >>" = appsec && echo -n true)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES -v -race -coverprofile=coverage.txt -covermode=atomic -tags "<< parameters.build_tags >>"

      - save_cache:
          key: go-mod-v5-core-<< parameters.gover >>-{{ checksum "go.sum.orig" }}
          paths:
            - "/home/circleci/go"

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results

      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  metadata:
    <<: *plain-go

    steps:
    - checkout

    # -mod=readonly is enabled by default starting in go1.16 causing many go
    # tools and editor integrations to report problems if the go.sum file is
    # not up-to-date, so let's make sure it is.
    - run:
        name: go.sum up-to-date
        command: |
          if ! go run -mod=readonly gosum.go; then
            # Older go versions, e.g. go1.14 will fail the check above with
            # the message below.
            #
            #   go: updates to go.sum needed, disabled by -mod=readonly
            #
            # Newer versions show which go.sum entries are missing. To get
            # useful CI errors for older versions, always print an explicit
            # diff when go.sum is not up-to-date.
            cp go.sum go.sum.before
            go mod tidy
            echo "--> go.sum diff:"
            diff go.sum.before go.sum
            exit 1
          fi
    - run:
        name: milestone
        command: |
          go run checkmilestone.go

    - run:
        name: copyright
        command: |
          go run checkcopyright.go

  lint:
    <<: *plain-go

    steps:
    - checkout

    - run:
        name: gofmt
        command: |
          if [ "$(gofmt -e -l . | wc -l)" -gt 0 ]; then
            exit 1
          fi

    - run:
        name: goimports
        command: |
          go install golang.org/x/tools/cmd/goimports
          if [ "$(~/go/bin/goimports -e -l -local gopkg.in/DataDog/dd-trace-go.v1 . | wc -l)" -gt 0 ]; then
            echo "Run 'goimports -w -local gopkg.in/DataDog/dd-trace-go.v1 .' to format code."
            ~/go/bin/goimports -d -local gopkg.in/DataDog/dd-trace-go.v1 .
            exit 1
          fi

    - run:
        name: lint
        command: |
          go get -u golang.org/x/lint/golint
          curl -L https://git.io/vp6lP | sh # https://github.com/alecthomas/gometalinter#binary-releases
          ./bin/gometalinter --disable-all --vendor --deadline=60s --enable=golint ./...

  test-outliers:
    parameters:
      gover:
        type: string
      build_tags:
        description: "go build tags to use to compile the tests"
        default: ""
        type: string
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    resource_class: xlarge
    working_directory: /home/circleci/dd-trace-go.v1
    docker:
      - image: circleci/golang:<< parameters.gover >>
        environment:
          GOPATH: "/home/circleci/go"
    steps:
      - checkout
      - run: cp go.sum go.sum.orig
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v5-outliers-<< parameters.gover >>-{{ checksum "go.sum.orig" }}

      - run:
          name: Enforce some dependencies
          command: |
            go get k8s.io/client-go@v0.17.0
            go get k8s.io/apimachinery@v0.17.0
            go get cloud.google.com/go/pubsub@v1.6.1
            # Temporarily enforce this version. 1.9.0 is incompatible with go < 1.16
            go get github.com/hashicorp/consul/api@v1.8.1
            # github.com/hashicorp/vault/sdk > v0.2.0 doesn't compile with go1.14
            go get github.com/hashicorp/vault/sdk@v0.2.0
            # Shopify/sarama > v1.22 doesn't compile with go1.14
            go get github.com/Shopify/sarama@v1.22.0

      - run:
          name: Testing outlier google.golang.org/api
          command: |
                go get google.golang.org/grpc@v1.29.0 # https://github.com/grpc/grpc-go/issues/3726
                # This step can fail and we don't care.
                #
                # This is here just to cover differences between older versions and newer versions of Go.
                # New versions of go won't be able to run tests unless the go.mod file is updated with go
                # mod tidy. Fortunately, new versions of go succeed at running go mod tidy.
                # Old versions of go don't need to run go mod tidy and will pull anything required when
                # running the tests. Coincidentally, they also fail to run go mod tidy for a reason I'm
                # not totally clear on. I guess the dependency resolution logic has changed a bit between
                # go versions.
                #
                # In short, running go mod tidy but allowing it to fail allows all versions of go we
                # support to run the tests successfully.
                GO111MODULE=on go mod tidy || exit 0
                go test -v ./contrib/google.golang.org/api/...

      - run:
          name: Testing outlier gRPC v1.2
          command: |
                # This hacky approach is necessary because running the tests regularly
                # do not allow using grpc-go@v1.2.0 alongside sketches-go@v1.0.0
                go mod vendor

                # Checkout grpc-go@v1.2.0
                cd vendor/google.golang.org && rm -rf grpc
                git clone git@github.com:grpc/grpc-go grpc && cd grpc
                git fetch origin && git checkout v1.2.0 && cd ../..

                # Checkout sketches-go@v1.0.0
                cd vendor/github.com/DataDog && rm -rf sketches-go
                git clone git@github.com:DataDog/sketches-go && cd sketches-go
                git fetch origin && git checkout v1.0.0 && cd ../..

                go test -mod=vendor -v ./contrib/google.golang.org/grpc.v12/...

      - save_cache:
          key: go-mod-v5-outliers-<< parameters.gover >>-{{ checksum "go.sum.orig" }}
          paths:
            - "/home/circleci/go"

      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

  test-contrib:
    parallelism: 4
    parameters:
      gover:
        type: string
      build_tags:
        description: "go build tags to use to compile the tests"
        default: ""
        type: string
    resource_class: xlarge
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
    working_directory: /home/circleci/dd-trace-go.v1
    docker:
      - image: circleci/golang:<< parameters.gover >>
        environment:
          GOPATH: "/home/circleci/go"
      - image: cassandra:3.7
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_PASSWORD: test
          MYSQL_USER: test
          MYSQL_DATABASE: test
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
      - image: consul:1.6.0
      - image: redis:3.2
      - image: elasticsearch:2
        environment:
          ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
      - image: elasticsearch:5
        environment:
          ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
      - image: elasticsearch:6.8.13
        environment:
          http.port: 9202-9300
          ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
      - image: elasticsearch:7.14.1
        environment:
          http.port: 9203-9300
          discovery.type: single-node
          ES_JAVA_OPTS: "-Xms750m -Xmx750m" # https://github.com/10up/wp-local-docker/issues/6
      - image: datadog/docker-dd-agent
        environment:
          DD_APM_ENABLED: "true"
          DD_BIND_HOST: "0.0.0.0"
          DD_API_KEY: invalid_key_but_this_is_fine
      - image: circleci/mongo:latest-ram
      - image: memcached:1.5.9
      - image: confluentinc/cp-zookeeper:5.0.0
        environment:
          ZOOKEEPER_CLIENT_PORT: "2181"
      - image: confluentinc/cp-kafka:5.0.0
        environment:
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_CREATE_TOPICS: gotest:1:1
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: cp go.sum go.sum.orig
      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v5-contrib-<< parameters.gover >>-{{ checksum "go.sum.orig" }}

      - restore_cache:
          keys:
          - v1-librdkafka-v1.3.0-{{ checksum "/etc/os-release" }}
      - run:
          name: Install librdkafka v1.3.0
          command: |
            if [ ! -d /tmp/librdkafka-v1.3.0 ] ; then
              echo "building librdkafka"
              git clone --branch v1.3.0 https://github.com/edenhill/librdkafka.git /tmp/librdkafka-v1.3.0
              (cd /tmp/librdkafka-v1.3.0 && ./configure && make)
            fi
            echo "installing librdkafka"
            (cd /tmp/librdkafka-v1.3.0 && sudo make install)
            sudo ldconfig
      - save_cache:
          key: v1-librdkafka-v1.3.0-{{ checksum "/etc/os-release" }}
          paths:
          - /tmp/librdkafka-v1.3.0

      - run:
          name: Enforce some dependencies
          command: |
            go get k8s.io/client-go@v0.17.0
            go get k8s.io/apimachinery@v0.17.0
            go get cloud.google.com/go/pubsub@v1.6.1
            # Temporarily enforce this version. 1.9.0 is incompatible with go < 1.16
            go get github.com/hashicorp/consul/api@v1.8.1
            # github.com/hashicorp/vault/sdk > v0.2.0 doesn't compile with go1.14
            go get github.com/hashicorp/vault/sdk@v0.2.0
            # Shopify/sarama > v1.22 doesn't compile with go1.14
            go get github.com/Shopify/sarama@v1.22.0

      - run:
          name: Tidy Modules
          # This step can fail and we don't care.
          #
          # This is here just to cover differences between older versions and newer versions of Go.
          # New versions of go won't be able to run tests unless the go.mod file is updated with go
          # mod tidy. Fortunately, new versions of go succeed at running go mod tidy.
          # Old versions of go don't need to run go mod tidy and will pull anything required when
          # running the tests. Coincidentally, they also fail to run go mod tidy for a reason I'm
          # not totally clear on. I guess the dependency resolution logic has changed a bit between
          # go versions.
          #
          # In short, running go mod tidy but allowing it to fail allows all versions of go we
          # support to run the tests successfully.
          command: GO111MODULE=on go mod tidy || exit 0

      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m

      - run:
          name: Wait for ElasticSearch (2)
          command: dockerize -wait http://localhost:9200 -timeout 1m

      - run:
          name: Wait for ElasticSearch (5)
          command: dockerize -wait http://localhost:9201 -timeout 1m

      - run:
          name: Wait for ElasticSearch (6)
          command: dockerize -wait http://localhost:9202 -timeout 1m

      - run:
          name: Wait for ElasticSearch (7)
          command: dockerize -wait http://localhost:9203 -timeout 1m

      - run:
          name: Wait for Datadog Agent
          command: dockerize -wait tcp://127.0.0.1:8126 -timeout 1m

      - run:
          name: Wait for Cassandra
          command: dockerize -wait tcp://localhost:9042 -timeout 2m

      - run:
          name: Wait for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m

      - run:
          name: Wait for Consul
          command: dockerize -wait http://localhost:8500 -timeout 1m

      - run:
          name: Testing integrations
          command: |
            PACKAGE_NAMES=$(go list ./contrib/... | grep -v -e grpc.v12 -e google.golang.org/api | circleci tests split --split-by=timings --timings-type=classname)
            export DD_APPSEC_ENABLED=$(test "<< parameters.build_tags >>" = appsec && echo -n true)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES -v -race -coverprofile=coverage.txt -covermode=atomic -tags "<< parameters.build_tags >>"

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results

      - save_cache:
          key: go-mod-v5-contrib-<< parameters.gover >>-{{ checksum "go.sum.orig" }}
          paths:
            - "/home/circleci/go"

      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build-and-test:
    jobs:
      - metadata
      - lint
      - test-core:
          matrix:
            parameters:
              gover: ["1.13", "1.14", "1.15", "1.16", "1.17"]
              build_tags: [ "", "appsec" ]
      - test-contrib:
          matrix:
            parameters:
              gover: ["1.14", "1.15", "1.16", "1.17"]
              build_tags: [ "", "appsec" ]
      - test-outliers:
          matrix:
            parameters:
              gover: ["1.14", "1.15", "1.16", "1.17"]
              build_tags: [ "", "appsec" ]
